### ISSUE TITLE
BUG: If you delete the last account you were viewing it breaks the extension

### ISSUE THREAD

**Issue by MattyIce** [MattyIce/steem-keychain#30]
If you select an account in the main drop down in keychain, and then go into manage accounts in settings and delete that account, it breaks the extension so you need to completely reset it and add all your accounts again to fix it.

![keychain bug](https://user-images.githubusercontent.com/2294614/46474436-e54cfe80-c7b0-11e8-84af-3e3d145565b2.JPG)

**Comment by MattyIce** [comment]
@stoodkev now i can't delete an account at all, I am getting this error:

```
popup.js:472 Uncaught TypeError: Cannot read property 'name' of null
    at popup.js:472
    at Array.filter (<anonymous>)
    at manageKeys (popup.js:471)
    at HTMLDivElement.<anonymous> (popup.js:181)
    at HTMLDivElement.dispatch (jquery.js:1627)
    at HTMLDivElement.q.handle (jquery.js:1589)
(anonymous) @ popup.js:472
manageKeys @ popup.js:471
(anonymous) @ popup.js:181
dispatch @ jquery.js:1627
q.handle @ jquery.js:1589
popup.html:1 Error in response to storage.get: TypeError: Cannot read property 'name' of null
    at chrome-extension://eelfpjmjcgdpgcejipjegponpjckpjem/js/popup.js:403:30
    at Object.callback (chrome-extension://eelfpjmjcgdpgcejipjegponpjckpjem/js/popup.js:402:47)
    at initializeMainMenu (chrome-extension://eelfpjmjcgdpgcejipjegponpjckpjem/js/popup.js:394:26)
    at Object.callback (chrome-extension://eelfpjmjcgdpgcejipjegponpjckpjem/js/popup.js:698:9)```
